---
# install languages and basic packages
- hosts: all
  become: true
  roles:
          - ansible-go
          - nodesource.node
          - {role: jdauphant.nginx, nginx_http_params: ["sendfile on", "access_log /var/log/nginx/access.log"]}
          - baseSetup
          - vimSetup
          - {role: PostgresConfig, become_user: postgres}
...
