---
          - name: copy config files to appropriate directories
            command: "cp {{item}}"
            with_items:
                    - /vagrant/static/.vimrc /home/vagrant/.vimrc
                    - /vagrant/static/.bash_profile /home/vagrant/.bash_profile
                    - /vagrant/static/default /etc/nginx/sites-available/default

          - name: create necessary directories
            file:
                path: "{{item}}"
                state: directory
                recurse: yes
            with_items:
                - /home/vagrant/go/src/github.com/nosequeldeebee
                - /home/vagrant/elm/src/github.com/nosequeldeebee
                - /home/vagrant/.vim/autoload
                - /home/vagrant/.vim/bundle

          - name: get pathogen module
            get_url:
                    url: https://tpo.pe/pathogen.vim
                    dest: /home/vagrant/.vim/autoload/pathogen.vim

          - name: get vim-plug
            get_url:
                    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
                    dest: /home/vagrant/.vim/autoload/plug.vim

          - name: clone git repos
            git:
                repo: "{{item.repo}}"
                dest: "{{item.dest}}"
            with_items:
                - { repo: 'git://github.com/tpope/vim-sensible.git', dest: '/home/vagrant/.vim/bundle/vim-sensible' }
                - { repo: 'https://github.com/scrooloose/syntastic.git', dest: '/home/vagrant/.vim/bundle/syntastic' }
                - { repo: 'https://github.com/fatih/vim-go.git', dest: '/home/vagrant/.vim/bundle/vim-go' }

          - name: install vim plugins
            shell: vim -c ":PlugInstall" -c q -c q -c q
            register: pluginsInstalled

          - name: install go packages
            command: "go get {{item}}"
            environment:
                PATH: /sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/go/bin
            with_items:
                    - golang.org/x/tools/cmd/goimports
                    - github.com/nsf/gocode
                    - github.com/rogpeppe/godef
                    - github.com/golang/lint/golint
                    - github.com/kisielk/errcheck
