---
          - name: ensure apt cache is up to date
            apt: update_cache=yes

          - name: install packages
            apt: name={{item}}
            with_items:
              - aptitude
              - git
              - postgresql
              - libpq-dev
              - python-psycopg2
              - vim

          - name: upgrade apt packages
            apt: upgrade=yes

          - name: install elm
            become: true
            command: "npm install -g {{item}}"
            with_items:
                    - elm
                    - elm-test
                    - elm-oracle
